// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateQuestionOptions implements pgx.CopyFromSource.
type iteratorForCreateQuestionOptions struct {
	rows                 []CreateQuestionOptionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateQuestionOptions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateQuestionOptions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].QuestionID,
		r.rows[0].Text,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForCreateQuestionOptions) Err() error {
	return nil
}

func (q *Queries) CreateQuestionOptions(ctx context.Context, arg []CreateQuestionOptionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"survey_question_options"}, []string{"id", "question_id", "text", "created_at"}, &iteratorForCreateQuestionOptions{rows: arg})
}
