// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type QuestionType string

const (
	QuestionTypeText           QuestionType = "text"
	QuestionTypeSingleChoice   QuestionType = "single_choice"
	QuestionTypeMultipleChoice QuestionType = "multiple_choice"
	QuestionTypeRating         QuestionType = "rating"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType `json:"question_type"`
	Valid        bool         `json:"valid"` // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

type RefreshToken struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	Revoked   bool      `db:"revoked" json:"revoked"`
}

type Survey struct {
	ID          uuid.UUID `db:"id" json:"id"`
	OwnerID     uuid.UUID `db:"owner_id" json:"owner_id"`
	Title       string    `db:"title" json:"title"`
	Description string    `db:"description" json:"description"`
	PublicID    string    `db:"public_id" json:"public_id"`
	IsActive    bool      `db:"is_active" json:"is_active"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type SurveyQuestion struct {
	ID         uuid.UUID    `db:"id" json:"id"`
	SurveyID   uuid.UUID    `db:"survey_id" json:"survey_id"`
	Text       string       `db:"text" json:"text"`
	Type       QuestionType `db:"type" json:"type"`
	IsRequired bool         `db:"is_required" json:"is_required"`
	CreatedAt  time.Time    `db:"created_at" json:"created_at"`
}

type SurveyQuestionOption struct {
	ID         uuid.UUID `db:"id" json:"id"`
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Text       string    `db:"text" json:"text"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type SurveySession struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	SurveyID  uuid.UUID   `db:"survey_id" json:"survey_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	IpAddress *netip.Addr `db:"ip_address" json:"ip_address"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
}

type SurveySessionAnswer struct {
	ID         uuid.UUID `db:"id" json:"id"`
	SessionID  uuid.UUID `db:"session_id" json:"session_id"`
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Answer     string    `db:"answer" json:"answer"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	Username     string             `db:"username" json:"username"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    time.Time          `db:"created_at" json:"created_at"`
	LastLogin    pgtype.Timestamptz `db:"last_login" json:"last_login"`
}
