// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: question_options.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createQuestionOption = `-- name: CreateQuestionOption :one
INSERT INTO survey_question_options (
    id, question_id, text,  created_at
) VALUES (
    $1, $2, $3, $4      
) RETURNING id, question_id, text, created_at
`

type CreateQuestionOptionParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Text       string    `db:"text" json:"text"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateQuestionOption(ctx context.Context, arg CreateQuestionOptionParams) (SurveyQuestionOption, error) {
	row := q.db.QueryRow(ctx, createQuestionOption,
		arg.ID,
		arg.QuestionID,
		arg.Text,
		arg.CreatedAt,
	)
	var i SurveyQuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

type CreateQuestionOptionsParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Text       string    `db:"text" json:"text"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

const deleteQuestionOption = `-- name: DeleteQuestionOption :exec
DELETE FROM survey_question_options
WHERE id = $1
`

func (q *Queries) DeleteQuestionOption(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestionOption, id)
	return err
}

const deleteQuestionOptionsByQuestion = `-- name: DeleteQuestionOptionsByQuestion :exec
DELETE FROM survey_question_options
WHERE question_id = $1
`

func (q *Queries) DeleteQuestionOptionsByQuestion(ctx context.Context, questionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestionOptionsByQuestion, questionID)
	return err
}

const listQuestionOptions = `-- name: ListQuestionOptions :many
SELECT id, question_id, text, created_at FROM survey_question_options
WHERE question_id = $1
`

func (q *Queries) ListQuestionOptions(ctx context.Context, questionID uuid.UUID) ([]SurveyQuestionOption, error) {
	rows, err := q.db.Query(ctx, listQuestionOptions, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SurveyQuestionOption
	for rows.Next() {
		var i SurveyQuestionOption
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestionOption = `-- name: UpdateQuestionOption :exec
UPDATE survey_question_options
SET
    text = $2
WHERE id = $1
`

type UpdateQuestionOptionParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Text string    `db:"text" json:"text"`
}

func (q *Queries) UpdateQuestionOption(ctx context.Context, arg UpdateQuestionOptionParams) error {
	_, err := q.db.Exec(ctx, updateQuestionOption, arg.ID, arg.Text)
	return err
}
