// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: survey.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO surveys (
    id, owner_id, title, description, public_id, is_active, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7          
)
RETURNING id, owner_id, title, description, public_id, is_active, created_at, updated_at
`

type CreateSurveyParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	OwnerID     uuid.UUID `db:"owner_id" json:"owner_id"`
	Title       string    `db:"title" json:"title"`
	Description string    `db:"description" json:"description"`
	PublicID    string    `db:"public_id" json:"public_id"`
	IsActive    bool      `db:"is_active" json:"is_active"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (Survey, error) {
	row := q.db.QueryRow(ctx, createSurvey,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.PublicID,
		arg.IsActive,
		arg.CreatedAt,
	)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.PublicID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSurvey = `-- name: DeleteSurvey :exec
DELETE FROM surveys
WHERE id = $1
`

func (q *Queries) DeleteSurvey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSurvey, id)
	return err
}

const getSurvey = `-- name: GetSurvey :one
SELECT id, owner_id, title, description, public_id, is_active, created_at, updated_at FROM surveys
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSurvey(ctx context.Context, id uuid.UUID) (Survey, error) {
	row := q.db.QueryRow(ctx, getSurvey, id)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.PublicID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSurveyWithQuestionsAndOptions = `-- name: GetSurveyWithQuestionsAndOptions :many
SELECT
    s.id as survey_id,
    s.owner_id as survey_owner_id,
    s.title as survey_title,
    s.description as survey_description,
    s.public_id as survey_public_id,
    s.is_active as survey_is_active,
    s.created_at as survey_created_at,
    s.updated_at as survey_updated_at,
    sq.id as question_id,
    sq.text as question_text,
    sq.type as question_type,
    sq.is_required as question_is_required,
    sq.created_at as question_created_at,
    sqo.id as option_id,
    COALESCE(sqo.text, '') as option_text,
    sqo.created_at as option_created_at
FROM surveys s
LEFT JOIN survey_questions sq ON s.id = sq.survey_id
LEFT JOIN survey_question_options sqo ON sq.id = sqo.question_id
WHERE s.id = $1
ORDER BY sq.created_at, sqo.created_at
`

type GetSurveyWithQuestionsAndOptionsRow struct {
	SurveyID           uuid.UUID          `db:"survey_id" json:"survey_id"`
	SurveyOwnerID      uuid.UUID          `db:"survey_owner_id" json:"survey_owner_id"`
	SurveyTitle        string             `db:"survey_title" json:"survey_title"`
	SurveyDescription  string             `db:"survey_description" json:"survey_description"`
	SurveyPublicID     string             `db:"survey_public_id" json:"survey_public_id"`
	SurveyIsActive     bool               `db:"survey_is_active" json:"survey_is_active"`
	SurveyCreatedAt    time.Time          `db:"survey_created_at" json:"survey_created_at"`
	SurveyUpdatedAt    time.Time          `db:"survey_updated_at" json:"survey_updated_at"`
	QuestionID         pgtype.UUID        `db:"question_id" json:"question_id"`
	QuestionText       string             `db:"question_text" json:"question_text"`
	QuestionType       NullQuestionType   `db:"question_type" json:"question_type"`
	QuestionIsRequired pgtype.Bool        `db:"question_is_required" json:"question_is_required"`
	QuestionCreatedAt  pgtype.Timestamptz `db:"question_created_at" json:"question_created_at"`
	OptionID           pgtype.UUID        `db:"option_id" json:"option_id"`
	OptionText         string             `db:"option_text" json:"option_text"`
	OptionCreatedAt    pgtype.Timestamptz `db:"option_created_at" json:"option_created_at"`
}

func (q *Queries) GetSurveyWithQuestionsAndOptions(ctx context.Context, id uuid.UUID) ([]GetSurveyWithQuestionsAndOptionsRow, error) {
	rows, err := q.db.Query(ctx, getSurveyWithQuestionsAndOptions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSurveyWithQuestionsAndOptionsRow
	for rows.Next() {
		var i GetSurveyWithQuestionsAndOptionsRow
		if err := rows.Scan(
			&i.SurveyID,
			&i.SurveyOwnerID,
			&i.SurveyTitle,
			&i.SurveyDescription,
			&i.SurveyPublicID,
			&i.SurveyIsActive,
			&i.SurveyCreatedAt,
			&i.SurveyUpdatedAt,
			&i.QuestionID,
			&i.QuestionText,
			&i.QuestionType,
			&i.QuestionIsRequired,
			&i.QuestionCreatedAt,
			&i.OptionID,
			&i.OptionText,
			&i.OptionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSurveysByOwner = `-- name: ListActiveSurveysByOwner :many
SELECT id, owner_id, title, description, public_id, is_active, created_at, updated_at FROM surveys
WHERE owner_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSurveysByOwner(ctx context.Context, ownerID uuid.UUID) ([]Survey, error) {
	rows, err := q.db.Query(ctx, listActiveSurveysByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Survey
	for rows.Next() {
		var i Survey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.PublicID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveysByOwner = `-- name: ListSurveysByOwner :many
SELECT id, owner_id, title, description, public_id, is_active, created_at, updated_at FROM surveys
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSurveysByOwner(ctx context.Context, ownerID uuid.UUID) ([]Survey, error) {
	rows, err := q.db.Query(ctx, listSurveysByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Survey
	for rows.Next() {
		var i Survey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.PublicID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSurvey = `-- name: UpdateSurvey :exec
UPDATE surveys
SET
    title = $2,
    description = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateSurveyParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Title       string    `db:"title" json:"title"`
	Description string    `db:"description" json:"description"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateSurvey(ctx context.Context, arg UpdateSurveyParams) error {
	_, err := q.db.Exec(ctx, updateSurvey,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.UpdatedAt,
	)
	return err
}
