// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: survey.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO surveys (
    id, owner_id, title, description, public_id, is_active, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7          
)
RETURNING id, owner_id, title, description, public_id, is_active, created_at
`

type CreateSurveyParams struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	OwnerID     uuid.UUID   `db:"owner_id" json:"owner_id"`
	Title       string      `db:"title" json:"title"`
	Description pgtype.Text `db:"description" json:"description"`
	PublicID    string      `db:"public_id" json:"public_id"`
	IsActive    bool        `db:"is_active" json:"is_active"`
	CreatedAt   interface{} `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (Survey, error) {
	row := q.db.QueryRow(ctx, createSurvey,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.PublicID,
		arg.IsActive,
		arg.CreatedAt,
	)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.PublicID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
