// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: survey.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO surveys (
    id, owner_id, title, description, public_id, is_active, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7          
)
RETURNING id, owner_id, title, description, public_id, is_active, created_at, updated_at
`

type CreateSurveyParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	OwnerID     uuid.UUID `db:"owner_id" json:"owner_id"`
	Title       string    `db:"title" json:"title"`
	Description string    `db:"description" json:"description"`
	PublicID    string    `db:"public_id" json:"public_id"`
	IsActive    bool      `db:"is_active" json:"is_active"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (Survey, error) {
	row := q.db.QueryRow(ctx, createSurvey,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.PublicID,
		arg.IsActive,
		arg.CreatedAt,
	)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.PublicID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSurvey = `-- name: DeleteSurvey :exec
DELETE FROM surveys
WHERE id = $1
`

func (q *Queries) DeleteSurvey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSurvey, id)
	return err
}

const getSurvey = `-- name: GetSurvey :one
SELECT id, owner_id, title, description, public_id, is_active, created_at, updated_at FROM surveys
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSurvey(ctx context.Context, id uuid.UUID) (Survey, error) {
	row := q.db.QueryRow(ctx, getSurvey, id)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.PublicID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSurveysByOwner = `-- name: ListActiveSurveysByOwner :many
SELECT id, owner_id, title, description, public_id, is_active, created_at, updated_at FROM surveys
WHERE owner_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSurveysByOwner(ctx context.Context, ownerID uuid.UUID) ([]Survey, error) {
	rows, err := q.db.Query(ctx, listActiveSurveysByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Survey
	for rows.Next() {
		var i Survey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.PublicID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveysByOwner = `-- name: ListSurveysByOwner :many
SELECT id, owner_id, title, description, public_id, is_active, created_at, updated_at FROM surveys
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSurveysByOwner(ctx context.Context, ownerID uuid.UUID) ([]Survey, error) {
	rows, err := q.db.Query(ctx, listSurveysByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Survey
	for rows.Next() {
		var i Survey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.PublicID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSurvey = `-- name: UpdateSurvey :exec
UPDATE surveys
SET
    title = $2,
    description = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateSurveyParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Title       string    `db:"title" json:"title"`
	Description string    `db:"description" json:"description"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateSurvey(ctx context.Context, arg UpdateSurveyParams) error {
	_, err := q.db.Exec(ctx, updateSurvey,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.UpdatedAt,
	)
	return err
}
