// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: survey_questions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSurveyQuestion = `-- name: CreateSurveyQuestion :one
INSERT INTO survey_questions (
    id, survey_id, text, type, is_required, created_at               
) VALUES (
    $1, $2, $3, $4, $5, $6 
) RETURNING id, survey_id, text, type, is_required, created_at
`

type CreateSurveyQuestionParams struct {
	ID         uuid.UUID    `db:"id" json:"id"`
	SurveyID   uuid.UUID    `db:"survey_id" json:"survey_id"`
	Text       string       `db:"text" json:"text"`
	Type       QuestionType `db:"type" json:"type"`
	IsRequired bool         `db:"is_required" json:"is_required"`
	CreatedAt  time.Time    `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateSurveyQuestion(ctx context.Context, arg CreateSurveyQuestionParams) (SurveyQuestion, error) {
	row := q.db.QueryRow(ctx, createSurveyQuestion,
		arg.ID,
		arg.SurveyID,
		arg.Text,
		arg.Type,
		arg.IsRequired,
		arg.CreatedAt,
	)
	var i SurveyQuestion
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.Text,
		&i.Type,
		&i.IsRequired,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM survey_questions
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getSurveyQuestion = `-- name: GetSurveyQuestion :one
SELECT id, survey_id, text, type, is_required, created_at FROM survey_questions
WHERE id = $1
`

func (q *Queries) GetSurveyQuestion(ctx context.Context, id uuid.UUID) (SurveyQuestion, error) {
	row := q.db.QueryRow(ctx, getSurveyQuestion, id)
	var i SurveyQuestion
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.Text,
		&i.Type,
		&i.IsRequired,
		&i.CreatedAt,
	)
	return i, err
}

const listRequiredSurveyQuestions = `-- name: ListRequiredSurveyQuestions :many
SELECT id, survey_id, text, type, is_required, created_at FROM survey_questions
WHERE survey_id = $1 AND is_required = true
`

func (q *Queries) ListRequiredSurveyQuestions(ctx context.Context, surveyID uuid.UUID) ([]SurveyQuestion, error) {
	rows, err := q.db.Query(ctx, listRequiredSurveyQuestions, surveyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SurveyQuestion
	for rows.Next() {
		var i SurveyQuestion
		if err := rows.Scan(
			&i.ID,
			&i.SurveyID,
			&i.Text,
			&i.Type,
			&i.IsRequired,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveyQuestions = `-- name: ListSurveyQuestions :many
SELECT id, survey_id, text, type, is_required, created_at FROM survey_questions
WHERE survey_id = $1
`

func (q *Queries) ListSurveyQuestions(ctx context.Context, surveyID uuid.UUID) ([]SurveyQuestion, error) {
	rows, err := q.db.Query(ctx, listSurveyQuestions, surveyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SurveyQuestion
	for rows.Next() {
		var i SurveyQuestion
		if err := rows.Scan(
			&i.ID,
			&i.SurveyID,
			&i.Text,
			&i.Type,
			&i.IsRequired,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSurveyQuestion = `-- name: UpdateSurveyQuestion :exec
UPDATE survey_questions
SET
    text = $2,
    type = $3,
    is_required = $4
WHERE id = $1
`

type UpdateSurveyQuestionParams struct {
	ID         uuid.UUID    `db:"id" json:"id"`
	Text       string       `db:"text" json:"text"`
	Type       QuestionType `db:"type" json:"type"`
	IsRequired bool         `db:"is_required" json:"is_required"`
}

func (q *Queries) UpdateSurveyQuestion(ctx context.Context, arg UpdateSurveyQuestionParams) error {
	_, err := q.db.Exec(ctx, updateSurveyQuestion,
		arg.ID,
		arg.Text,
		arg.Type,
		arg.IsRequired,
	)
	return err
}
